imports:
    - { resource: "@Tavy315SyliusQuotesPlugin/Resources/config/app/grids.yaml" }

services:
    tavy315_sylius_quotes.context.quote:
        arguments:
            - "@tavy315_sylius_quotes.repository.customer_quote"
            - "@security.token_storage"
        class: Tavy315\SyliusQuotesPlugin\Context\QuoteContext
        public: true

    Tavy315\SyliusQuotesPlugin\Context\QuoteContextInterface:
        alias: tavy315_sylius_quotes.context.quote

    tavy315_sylius_quotes.controller.action.list_quote_products:
        arguments:
            - "@tavy315_sylius_quotes.context.quote"
            - "@tavy315_sylius_quotes.repository.product"
            - "@twig"
            - "@sylius.context.shopper"
        class: Tavy315\SyliusQuotesPlugin\Controller\Action\ListQuoteProductsAction
        tags:
            - { name: controller.service_arguments }
