sylius_grid:
    templates:
        action:
            quote: "@Tavy315SyliusQuotesPlugin/Account/CustomerQuote/Grid/Action/quote.html.twig"
    grids:
        tavy315_sylius_quotes_shop_account_quote:
            driver:
                name: doctrine/orm
                options:
                    class: "%tavy315_sylius_quotes.model.customer_quote.class%"
                    repository:
                        method: createByCustomerQueryBuilder
                        arguments:
                            - "expr:service('sylius.context.customer').getCustomer().getId()"
            sorting:
                documentDate: desc
            fields:
                documentNo:
                    type: twig
                    label: tavy315_sylius_quotes.ui.document_no
                    sortable: ~
                    options:
                        template: "@Tavy315SyliusQuotesPlugin/Account/CustomerQuote/Grid/Field/document_no.html.twig"
                documentDate:
                    type: datetime
                    label: tavy315_sylius_quotes.ui.document_date
                    sortable: ~
                    options:
                        format: d/m/Y
                totalAmount:
                    type: twig
                    label: tavy315_sylius_quotes.ui.total_amount
                    path: .
                    sortable: totalAmount
                    options:
                        template: "@Tavy315SyliusQuotesPlugin/Account/CustomerQuote/Grid/Field/total_amount.html.twig"
            actions:
                item:
                    show:
                        type: shop_show
                        label: sylius.ui.show
                        options:
                            link:
                                route: tavy315_sylius_quotes_shop_account_quote_products
                                parameters:
                                    document: resource.documentNo
